<?xml version="1.0" encoding="UTF-8"?><testrun name="UserControllerTest" project="TaskTracker" tests="11" started="11" failures="0" errors="1" ignored="0">
  <testsuite name="com.capsule.TaskTracker.componentTest.UserControllerTest" time="2.508">
    <testcase name="createUserNegTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="1.977"/>
    <testcase name="retreiveUserList" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.146"/>
    <testcase name="getUserByProjectIdTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.033"/>
    <testcase name="retrieveUserNegTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.168">
      <error>org.mockito.exceptions.base.MockitoException: 
Checked exception is invalid for this method!
Invalid: java.lang.Exception&#13;
	at com.capsule.TaskTracker.componentTest.UserControllerTest.retrieveUserNegTest(UserControllerTest.java:106)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:498)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)&#13;
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)&#13;
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)&#13;
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)&#13;
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)&#13;
&#13;
</error>
    </testcase>
    <testcase name="updateUserNegTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.009"/>
    <testcase name="updateUserTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.069"/>
    <testcase name="createUserTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.014"/>
    <testcase name="retrieveUserExcepTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.013"/>
    <testcase name="deleteUserNegTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.05"/>
    <testcase name="retrieveUserTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.009"/>
    <testcase name="deleteUserTest" classname="com.capsule.TaskTracker.componentTest.UserControllerTest" time="0.018"/>
  </testsuite>
</testrun>
